linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/container/container.go
      text: "Error return value of .((os|io)\\..*|.*Close|.*Flush|.*Write|.*Sync) is not checked"
      linters:
        - errcheck 